cookie:
  expiry_days: 1
  key: qwertyuiop
  name: cook
credentials:
  usernames:
    admin:
      email: admin.admin01@gmail.com
      failed_login_attempts: 0
      logged_in: true
      name: admin
      password: admin
pre-authorized:
  emails:
  - admin.admin01@gmail.com
